### PR TITLE
refactor(svelte-table): improve type inference

### PR DESCRIPTION
**Pull request by thenbe**
`svelte-check` was having a difficult time inferring the props types when using svelte 5. This PR fixes that by swapping out the deprecated type utilities to improve type inference for `renderComponent(component, props)`.

Also updates svelte from `svelte@5.0.0-next.78` to `svelte@5.0.0-next.155`.

### CODE REVIEW

**Comment by KevinVandy** [comment]
@thenbe I can't get the sorting example types to compile, but also cannot get the error to appear in the editior.

**Comment by thenbe** [comment]
Yeah I see the same issue. After running `pnpm update --latest` in the root of the repo and the sorting example types can compile again. So I guess some dependencies in the lockfile must be old.

**Comment by thenbe** [comment]
I'm not sure how to find the exact culprit though.

**Comment by thenbe** [comment]
The sorting example is the only one failing (out of the other svelte examples) is because it's the only that actually uses `renderComponent`.

**Comment by thenbe** [comment]
Updated deps for svelte examples using `pnpm update --filter './examples/svelte/*'`. Both `build` and `test:types` now work in all svelte examples.

**Comment by KevinVandy** [comment]
be sure to run `pnpm test` before pushing up. Still some type issues.

**Comment by KevinVandy** [comment]
Think we got all the right versions upgraded repo wide now

**Review by KevinVandy — APPROVED** [review]

**Pull request merged**
