### PR TITLE
create simple non-grouped columns react example

### PR DESCRIPTION
**Pull request by KevinVandy**
Enough people have asked for a simpler example since the "basic" example is not simple enough 🤷 

Can follow up with Solid, Svelte, and Vue examples

### CODE REVIEW

**Comment by tannerlinsley** [comment]
Sounds good. Let's name this new one `basic` and move the existing basic to be `column-groups`?

**Comment by tannerlinsley** [comment]
Or would you rather keep the basic with groups?

**Comment by KevinVandy** [comment]
> Sounds good. Let's name this new one `basic` and move the existing basic to be `column-groups`?

I agree. I'll update this PR to include the other adapter examples too

**Comment by KevinVandy** [comment]
I had originally also updated this for Vue, but could not get any Vue sandboxes to work online, or locally.

Basic and Column Groups examples updated/created for React, Solid, and Svelte

**Pull request merged**
