### PR TITLE
Add React Kitchen Sink Example

### PR DESCRIPTION
**Pull request by fekete965**
Adding `kitchen-sink` to react examples:

1. Sorting
2. Pagination
3. Filtering
4. Resizable Columns
5. Column Visibility
6. Header Grouping
7. Table Pins
8. Row Selection

Screenshots:
Screenshot 2022-08-01 at 22 51 20
Screenshot 2022-08-01 at 22 51 30

### CODE REVIEW

**Comment by fekete965** [comment]
I will investigate the failure as soon as I have a bit more time this week!

**Comment by fekete965** [comment]
#4232 seems to have a working solution regarding the workflow failure.

**Comment by KevinVandy** [comment]
I tried to get this running, but for some reason could not. I know its been a long time so this PR might be abandoned

**Comment by fekete965** [comment]
@KevinVandy I'll need to update this, sorry for that! I believe certain parts of the API have changed.

**Comment by KevinVandy** [comment]
> @KevinVandy I'll need to update this, sorry for that! I believe certain parts of the API have changed.

@fekete965  yep, not blaming you at all. I'm going through and cleaning up PRs. Couldn't quite find a way to include this one yet. 

If you do work on it, include entries for this example in the `tsconfig.josn` and `package.json` in order to yarn link everything together correctly for local development

**Comment by fekete965** [comment]
@KevinVandy I fixed the broken code bits and added the missing entry the tsconfig and package.json

**Comment by fekete965** [comment]
@KevinVandy you might be able to point me in the right direction.
Typecheck passes locally but fails here.

For some reason `react-bootstrap` causing some issues:
```
Error: examples/react/bootstrap/src/main.tsx(6,33): error TS2307: Cannot find module 'react-bootstrap' or its corresponding type declarations.
```

I have both `bootstrap` and `react-bootstrap` installed in the bootstrap example, I am not sure why TS throws an error. 😞

**Comment by KevinVandy** [comment]
@fekete965 Did you merge main into your branch?

**Comment by fekete965** [comment]
@KevinVandy no, I didn't. I synchronised my forked repo, pulled main and rebased the PR on it.

**Comment by fekete965** [comment]
@KevinVandy I managed to miss the bootstrap out of the package.json... 🤦   This caused the described issue above.

**Review by KevinVandy — APPROVED** [review]

**Comment by KevinVandy** [comment]
@fekete965  There are now conflicts. You may need to merge in main or rebase again

**Comment by fekete965** [comment]
@KevinVandy Thank you!
I assume the conflict got resolved since the PR's been merged ? 🤔

**Comment by KevinVandy** [comment]
> @KevinVandy Thank you!
> I assume the conflict got resolved since the PR's been merged ? 🤔 

Yeah I did it through the browser

**Comment by fekete965** [comment]
Amazing! Thank you for your help! 🙏

**Pull request merged**
