### PR TITLE
feat: column/cell/header value types

### PR DESCRIPTION
**Pull request by tannerlinsley**

### CODE REVIEW

**Review by KevinVandy — APPROVED** [review]
I think this is good. Easier than the `as unknown as myType`, though maybe devs will make TypeScript lie to themselves this way 🤷🏻‍♂️

**Review by fekete965 — APPROVED** [review]
So much batter than my "approach" 😅

**Comment by tannerlinsley** [comment]
You can now extend these core types like so:

```tsx
// Could also be the core or any other adapter
declare module '@tanstack/react-table' {
  interface TableMeta {
    foo: string
  }

  interface ColumnMeta {
    bar: number
  }

  interface FilterMeta {
    rank: number
  }
}
```

**Review by fekete965 — APPROVED** [review]

**Comment by Martijn-Schoenmaker-Webbio** [comment]
Is is just me or does this still not solve the getValue() types? When creating new columnDefs like this `ColumnDef<MyType>`
the `row.getValue()` is still unknown. This used to be no problem in the beta.

Or am I missing someting?

**Comment by bazalp** [comment]
> Oui, il semble qu'il retourne inconnu. :/
> 
> Capture d&apos;écran 2022-07-12 à 15 15 07

I see the same problem

**Pull request merged**
