### PR TITLE
fix: filter should filter out null values

### LINKED ISSUE #4245: [v8] Filter not working if accessorFn returns null for any row
### Describe the bug

Filtering a column defines like:

```
{
        id: 'name',
        header: 'Name',
        accessorKey: 'name',
}
```

works, even if that column has null values.

Now when doing 

```
{
        id: 'name',
        header: 'Name',
        accessorFn: (row) => row.name !== 'ignore' ? row.name : null,
}
```

in this case filtering does not work anymore at all.
So even not for the rows returning a value.

I can use this workaround:

```
{
        id: 'name',
        header: 'Name',
        accessorFn: (row) => row.name !== 'ignore' ? row.name : '',
}
```

but this should not be needed I would say.

### Your minimal, reproducible example

-

### Steps to reproduce

See above.

### Expected behavior

Rows with actual value to be filtered succesfully.

### How often does this bug happen?

Every time

### Screenshots or Videos

_No response_

### Platform

macOS

### react-table version

v8.5.1, v.8.5.2

### TypeScript version

v4.7.4

### Additional context

_No response_

### Terms & Code of Conduct

- [X] I agree to follow this project's Code of Conduct
- [X] I understand that if my bug cannot be reliable reproduced in a debuggable environment, it will probably not be fixed and this issue may even be closed.

### PR DESCRIPTION
**Pull request by simPod**
Fixes #4245

### CODE REVIEW

**Comment by simPod** [comment]
@tannerlinsley I suppose the `autoRemove` should somehow get involved so maybe my fix is in wrong direction?

Though I was thinking those tests might be valuable nonetheless.

**Comment by stephanvdhorn** [comment]
We currently experience problems because some of our values are null, so could this get a higher priority?

**Comment by ahammouda** [comment]
This is also super useful if you are trying to run filter functions over virtualized rows - I've copied the filter function in a project just to get me over that hurdle.  Definitely +1.

**Comment by KevinVandy** [comment]
You guys can override the filter fns with your own custom ones to fit your requirements

**Comment by simPod** [comment]
Ofc but that's not a solution that benefits others nor systematic one. I'd like to solve it on library level though workaround are possible.

**Comment by KevinVandy** [comment]
Closing this in favor of #4441, as it got fixed in v8.5.26

**Pull request closed without merging**
